name: soham workflow

on :
    push:
      
jobs:
    build: #job ka naam 
        runs-on: ubuntu-latest #GitHub Runner (free)
        steps:
          - name: checkout code
            uses: actions/checkout@v4 #github repository ko clone karta hai into ubuntu runner 

          - name: Setup Docker  
            uses: docker/setup-buildx-action@v4 
          


    